### ISSUE TITLE
Less verbose

### ISSUE THREAD

**Issue by brorhb** [fluttercommunity/flutter_downloader#107]
Is there something I can do to make the plugin less verbose in it's outputs? I can get pretty hard to use when you try to log stuff in other parts of an application while this package is running 😰

**Comment by hnvn** [comment]
Why don't you use filter? Every log comes with a tag

**Comment by brorhb** [comment]
Aah! Can you point me to any documentation?

**Comment by jpcarreira** [comment]
I'm also interested in making it less verbose. @brorhb, did you manage to do it?

**Comment by nioncode** [comment]
@hnvn Logging really should be configurable, especially since URLs, filenames, and most importantly headers are logged, which might contain **authentication credentials**, which are then logged in plaintext.

Further, logging to logcat is only helpful in debugging locally and does not help when running the app in the field, since there is no access to the logcat output anyways.

Thus, I would greatly appreciate if you could a) add a simple configuration flag to turn off all logging and enable this by default (as a good security practice), and/or b) allow a logging callback to be provided so that we can customize where to log (e.g. to Crashlytics, Sentry, etc.).

**Comment by brorhb** [comment]
> I'm also interested in making it less verbose. @brorhb, did you manage to do it?

Sorry for the late answer. I really found the package to complex for what I wanted. And created my own donwloader in a couple of days 🤓 that is unfortunately a private repo since it’s work related 🙈

**Comment by nioncode** [comment]
Ironically this is what I also did with the help of https://github.com/vrtdev/flutter_workmanager, which was trivial to do and does not leak any private information in logs or the database.

**Comment by hnvn** [comment]
You now can disable printing logs to console in v1.4.4
