### ISSUE TITLE
call to initialize() crash on iPad 3 (md366bz/a) with iOS 9.3.6

### ISSUE THREAD

**Issue by danielns1982** [fluttercommunity/flutter_downloader#150]
methodCallHandler: initialize
startBackgroundIsolate
Lost connection to device.
*** Assertion failure in -[FlutterDownloaderPlugin startBackgroundIsolate:], /Users/danielnsilva/Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.3.1/ios/Classes/FlutterDownloaderPlugin.m:113
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'failed to find callback'
	*** First throw call stack:
	(0x2555391b 0x24ceee17 0x255537f1 0x25d37529 0x1df4445 0x1df9381 0x1dfcdeb 0x2bf3e1 0x26f99f 0x2b4953 0x27b339 0x27e7f7 0x2551658f 0x255161c1 0x2551400d 0x25463229 0x25463015 0x26a53ac9 0x29b37189 0xe074d 0x2510b873)
Exited (sigterm)

**Comment by StarSkyK** [comment]
did u update to 1.3.2 ?  method was changed , read document again

**Comment by Gicminos** [comment]
I have the same problem with 1.3.3

**Comment by MiroCaseiro** [comment]
Same problem here.

**Comment by antonioBest** [comment]
Same problem with 1.3.3

**Comment by axtro** [comment]
I am not an objective c programmer, but I think that the problem is the conversion of the handle argument in initializeMethodCall:

```
- (void)initializeMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result {
    NSArray *arguments = call.arguments;
    NSLog(@"arguments: %@", arguments);
    [self startBackgroundIsolate:[arguments[0] longLongValue]];
    result([NSNull null]);
}
```
But, I don't know the consequences of doing that change.

Anyway, I have created a pull request in case you consider it useful.

https://github.com/fluttercommunity/flutter_downloader/pull/199

**Comment by robe5** [comment]
I am not an objective c programmer, but I think that the problem is the conversion of the handle argument in initializeMethodCall:

```
- (void)initializeMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result {
    NSArray *arguments = call.arguments;
    NSLog(@"arguments: %@", arguments);
    [self startBackgroundIsolate:[arguments[0] longLongValue]];
    result([NSNull null]);
}
```
But, I don't know the consequences of doing that change.

Anyway, I have created a pull request in case you consider it useful.

https://github.com/fluttercommunity/flutter_downloader/pull/199
