### ISSUE TITLE
Its possible to change the notification layout?

### ISSUE THREAD

**Issue by LuisCampos97** [fluttercommunity/flutter_downloader#369]
Hi!
I want this Google Chrome notification layout for example where these two labels change. It's possible?

![imagem](https://user-images.githubusercontent.com/33434500/98983047-2c715600-2518-11eb-802e-30965d106ba1.png)

Instead of this layout by default:

![imagem](https://user-images.githubusercontent.com/33434500/98983137-4874f780-2518-11eb-8d22-11fb9626ee90.png)

Thank you!

**Comment by hnvn** [comment]
It's impossible in current implementation. Changing notification layout needs manipulation on native side. In order to support this feature, the plugin needs to pre-define some kinds of notification layout and expose a API on Dart codes that lets user pass layout configuration from Flutter side. It would take time and much effort, I don't have a plan to support it. Thanks for your feedback
