### ISSUE TITLE
Any idea I get version error with  'android.arch.core:runtime'?

### ISSUE THREAD

**Issue by dwengticorp** [fluttercommunity/flutter_downloader#44]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.core:runtime' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

**Comment by hnvn** [comment]
There're many questions like this in stackoverflow:
https://stackoverflow.com/search?q=android+gradle+dependencies+version+conflict

**Comment by wyxcoder** [comment]
I can sure google the solution, I actually did. There are several reasons why I posted here for help.
1, I spent hours google for solution, but could not fix it.
2, The error only happened with flutter_downloader, once it is removed, everything is fine.
3, I tried to use old version like 1.0.0 of the downloader, still get same error. I wonder what is the special in downloader, since I don't have problem with a dozen other plug-ins

**Comment by hnvn** [comment]
Have you tried the following config yet?

```
configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('android.arch.core' == details.requested.group && 'runtime' == details.requested.name) {
                    details.useVersion '1.1.1'
                }

            }
        }
    }
```

**Comment by gitzhangliang** [comment]
configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('android.arch.core' == details.requested.group && 'runtime' == details.requested.name) {
                    details.useVersion '1.1.1'
                }

            }
        }
    }

I should add code to where?  build.gradle?

**Comment by gitzhangliang** [comment]
Where should I add this code?  build.gradle? under android/build.gradle  or android/app/build.gradle? or other file?
