### ISSUE TITLE
Not working in Android 11

### ISSUE THREAD

**Issue by cbanaspk** [fluttercommunity/flutter_downloader#492]
Code executes flawlessly in every version besides android 11.

Here is a snippet that works on every android besides 11.
 
  ReceivePort receivePort = ReceivePort();
  int progress = 0;

  @override
  void initState() {
    super.initState();
    startFlutterDownloader();
  }

  void startFlutterDownloader() async {
    if (!globals.webPlatform) {
      print("booting up");
      WidgetsFlutterBinding.ensureInitialized();
      await FlutterDownloader.initialize(
          debug: true // optional: set false to disable printing logs to console
      );
      IsolateNameServer.registerPortWithName(
          receivePort.sendPort, "downloading");
      receivePort.listen((message) {
        this.setState(() {
          progress = message;
        });
        print(message);
      });
      FlutterDownloader.registerCallback(downloadCallBack);
    }
  }

  static void downloadCallBack(id, status, progress) {
    final SendPort? sendPort = IsolateNameServer.lookupPortByName(
        'downloading');
    sendPort!.send(progress);
  }

  void mobileDownload(filename) async {
    final status = await Permission.storage.request();
    if (status.isGranted) { //user grants download permission
      var storagePath;
      if(globals.androidPlatform){
        storagePath = await getExternalStorageDirectory();
      } else if (globals.iosPlatform){
        storagePath = await getApplicationDocumentsDirectory();
      }
      final taskId = await FlutterDownloader.enqueue(
        url: 'https://www.fnordware.com/superpng/pnggrad16rgb.png',
        savedDir: storagePath.path,
        fileName: filename,
        showNotification: true, // show download progress in status bar (for Android)
        openFileFromNotification: true, // click on notification to open downloaded file (for Android)
      );
    }
  }

**Comment by arshadbarves** [comment]
Its works fine in android 11 I have tested it. Can you explain in which area you face issues

**Comment by cbanaspk** [comment]
> Its works fine in android 11 I have tested it. Can you explain in which area you face issues

I see you have replied in a few threads that it is working for your android 11. Can you show your build.gradle, ANdroidManifest, and pubsec files?

**Comment by docputs** [comment]
I'm also facing a similar problem, as I can't open the file from the notification bar after it is downloaded. Today I cloned this package and deployed the example app to my physical device, which has Android 11 installed, and I couldn't make it work either

**Comment by arshadbarves** [comment]
AndriodManifest
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.videodown">
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"></uses-permission>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"></uses-permission>
    <uses-permission android:name="android.permission.INTERNET"></uses-permission>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE " />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <application
        android:label="videodown"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config"
        tools:replace="android:label" 
        android:requestLegacyExternalStorage="true">
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            tools:node="remove" />

        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="false">
            
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="5" />
        </provider>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
               
               <data
                   android:scheme="https"
                   android:host="example.com"
                   android:pathPrefix="/invite"/>
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="*/*" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.SEND_MULTIPLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="*/*" />
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`

build.gradle

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.videodown"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
`

pubsec

`name: videodown
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_zoom_drawer: ^2.0.2+4
  convex_bottom_bar: ^3.0.0
  font_awesome_flutter: ^9.1.0
  material_floating_search_bar: ^0.3.4
  provider: ^5.0.0
  http: ^0.13.3
  cupertino_icons: ^1.0.3
  animations: ^2.0.0
  google_fonts: ^2.1.0
  dio: ^4.0.0
  filesize: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  flutter_downloader: ^1.6.1
  permission_handler: ^8.1.2
  path_provider: ^2.0.2
  receive_sharing_intent: ^1.4.5
  system_alert_window: ^0.5.0
  another_flushbar: ^1.10.24
  double_back_to_close: ^2.0.0
  get: ^4.1.4
  flutter_ffmpeg: ^0.4.0
  youtube_explode_dart: ^1.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by YeDaxia** [comment]
not work in android 11 too~ others is fine.

**Comment by erperejildo** [comment]
when the download fails, can you get any logs to check why it is failing?

**Comment by mehul425** [comment]
https://github.com/fluttercommunity/flutter_downloader/issues/488#issuecomment-891556675
https://stackoverflow.com/questions/66557956/creating-a-csv-file-in-android-11-return-error-java-io-filenotfoundexception-e

I was facing same issue.
But after replace ":" with "." in file name its working fine.

**Comment by flutternoob** [comment]
I read somewhere that with Android 11, one cannot access external storage directories. Try using ```path_provider``` to get application support or temporary directories, i.e, keep downloaded files within the app's sandbox.
