### ISSUE TITLE
Not work in iOS 15 

### ISSUE THREAD

**Issue by FernandoGonz** [fluttercommunity/flutter_downloader#569]
Not work in iOS 15 library version 1.7.1

**Comment by aravind-b-dev** [comment]
use this for download directory    

    directory = await getExternalStorageDirectory();

**Comment by Sclll** [comment]
getExternalStorageDirectory() is used just for Android. Not for ios. And I had similar problem.
`open DB successfully
Query was executed successfully. Affected rows = 1
savedDir: /var/mobile/Containers/Data/Application/3DD5D452-F347-497C-AAE5-EFB1B2BBC3FC/Documents/iosdown/314
filename: f_314.ipa
Unable to copy temp file. Error: The file “CFNetworkDownload_hKevdz.tmp” couldn’t be opened because you don’t have permission to view it.`

**Comment by bartekpacia** [comment]
Since there's no response, I'm gonna assume that the answer provided by @aravind-b-dev helped. Feel free to comment/reopen if the issue persists.
