### ISSUE TITLE
flutter_downloader doesn't show notification of downloading in iOS

### ISSUE THREAD

**Issue by ayezarniaung** [fluttercommunity/flutter_downloader#668]
**Describe the bug**

[flutter_downloader doesn't show notification of downloading in iOS]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Device information:**

- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 15.4]
- plugin version [e.g. v1.8.0]

**Additional context**

**Comment by bartekpacia** [comment]
I think that you might be missing the permission for showing notifications. This plugin doesn't implement this feature, unfortunately.

BTW, please follow the issue template – it's here so that I can at least try to reproduce your problem. Without this info, I have no other choice but to close this issue.
