### ISSUE TITLE
_AssertionError ('package:flutter_downloader/src/downloader.dart': Failed assertion: line 124 pos 12: '_initialized': plugin flutter_downloader is not initialized)

### ISSUE THREAD

**Issue by innovatoraakash** [fluttercommunity/flutter_downloader#679]
_AssertionError ('package:flutter_downloader/src/downloader.dart': Failed assertion: line 124 pos 12: '_initialized': plugin flutter_downloader is not initialized)

I can download files but when I run loadTask  or loadTaskWithQuery it asserts this error
note: I have initialized flutterdownloader in main

**Comment by ImranR98** [comment]
I had the same issue, turns out I was calling `loadTask` from inside the callback (the function kept in `registerCallback`). That callback runs in a "background" process where `FlutterDownloader` is not initialized, so instead the data should be forwarded to a foreground function (as shown in the `README.md`), where `loadTask` should work.

**Comment by innovatoraakash** [comment]
> I had the same issue, turns out I was calling `loadTask` from inside the callback (the function kept in `registerCallback`). That callback runs in a "background" process where `FlutterDownloader` is not initialized, so instead the data should be forwarded to a foreground function (as shown in the `README.md`), where `loadTask` should work.

Yes calling the query from inside callback resulted into this 
solved
