### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by ShashankSirmour** [fluttercommunity/flutter_downloader#76]
I am getting errors when I add these two packages together, please help

admob_flutter: ^0.3.1
flutter_downloader: ^1.1.7

**Comment by hnvn** [comment]
what's kind of error?

**Comment by ShashankSirmour** [comment]
ms] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
[   +3 ms] D8: Program type already present: android.support.v4.app.INotificationSideChannel
[   +3 ms] 61 actionable tasks: 5 executed, 56 up-to-date
[        ] FAILURE: Build failed with an exception.

**Comment by ShashankSirmour** [comment]
flutter_pdfview: ^1.0.0+4
flutter_downloader: ^1.1.7


these both also give me the same  error

when I install flutter_downloader: ^1.1.7 whit these packages then I get an error please help flutter_downloader is a great library I can't compromise with it

**Comment by ShashankSirmour** [comment]
i think its androidX

**Comment by ShashankSirmour** [comment]
but after android migration i am getting 27 more warning like this
Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath

**Comment by hnvn** [comment]
Have a look at: https://medium.com/mindorks/avoiding-conflicts-in-android-gradle-dependencies-28e4200ca235, it might be helpful

**Comment by ShashankSirmour** [comment]
thank you @hnvn  for four kind help thank you very much it's all happened because of androidX

**Comment by Moonwing** [comment]
> but after android migration i am getting 27 more warning like this
> Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath

I have the same problem . I'm so grateful if you tell me  the way to solve it

In android/gradle.properties, i have append

android.enableJetifier=true
android.useAndroidX=true

  and I have tired then old version before Androidx . but it  looks useless ，

As soon as I try to build
   FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.1) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
