### ISSUE TITLE
.doc .docx .xls .xlsx unable to open

### ISSUE THREAD

**Issue by steph-laporte** [fluttercommunity/flutter_downloader#812]
Using the example provided with flutter_downloader, saving downloaded files in public storage, trying to open .doc file shows "Cannot open this file". 
Going to the app "Files" inside "Download" folder there file is opening without any problem with "google doc" app or "office 365" app.
.pdf and .jpg image files open without any problem. 
Have any idea to solve this ?

**Comment by rekire** [comment]
Assuming that you are talking about Android:
This is likely the way how the download is provided for other apps. When I remember correctly then a content provider is used for that. It's not very unlikely that those apps do not support opening files from the content provider as streams. Just as file path or the scoped storage which is both currently not supported on devices with Android 10+.

**Comment by bartekpacia** [comment]
Thanks for explaining, @rekire!

**Comment by griff88** [comment]
Have the same problem too with docx/xlsx files. Trying to open those file types in several device types using Android 12 or 13 will result in failure. For a workaround currently we asked the user to download another app which can open those files (other than the pre-supplied Office 365) which will trigger "Open with..." prompt on the app.

**Comment by griff88** [comment]
> Assuming that you are talking about Android: This is likely the way how the download is provided for other apps. When I remember correctly then a content provider is used for that. It's not very unlikely that those apps do not support opening files from the content provider as streams. Just as file path or the scoped storage which is both currently not supported on devices with Android 10+.

@rekire, I found a case where two phones of same model (Redmi Note Pro 10 on Android 12) which has different behaviour in this issue. I cloned the example app, changed one of the links to a link to PPTX file and tried to download it. Both have no issues in downloading but one phone can open the downloaded file while the other one cannot. I found it weird because both phones only have WPS as their supplied app for opening Office files (docx/xlsx/pptx). Could you point me out what I might have missed?
